f = open('/Users/jeongyoonlee/PycharmProjects/numerical-analysis/chapter_3/test.txt', 'a')
f.write('\n첫번째시도입니다.\n')
f.write('두 번째 줄 추가입니다.\n')
f.close()
f = open('/Users/jeongyoonlee/PycharmProjects/numerical-analysis/chapter_3/test.txt', 'a')
f.write('\n첫번째시도입니다.\n')
f.write('두 번째 줄 추가입니다.\n')
f.close()
f = open('/Users/jeongyoonlee/PycharmProjects/numerical-analysis/chapter_3/test.txt', 'a')
f.write('\n첫번째시도입니다.\n')
f.write('두 번째 줄 추가입니다.\n')
f.close()
f = open('/Users/jeongyoonlee/PycharmProjects/numerical-analysis/chapter_3/test.txt', 'a')
f.write('\n첫번째시도입니다.\n')
f.write('두 번째 줄 추가입니다.\n')
f.close()